### ISSUE TITLE
Help with Jaxon Upload

### ISSUE THREAD

**Issue by kskelton2021** [jaxon-php/jaxon-upload#1]
Im not sure how to set this up.

My file tree looks like this:
assets/vendors/jaxon/4.1.0/jaxon-upload

I dont know where i go from here.

In version 3 it was working like a charm but now no clue where to start with setting this up and making it work.

Help please!

An HTML example with the Jaxon PHP tie in would be good.

Thanks.

**Comment by feuzeu** [comment]
Hi,

The upload feature is disabled by default in Jaxon v4.
You will need to set the `core.upload.enabled` option to `true` to enable upload.

Note that Jaxon global functions are moved to the `Jaxon` namespace.
So if you are using one of the functions defined in [https://github.com/jaxon-php/jaxon-core/blob/master/src/start.php](https://github.com/jaxon-php/jaxon-core/blob/master/src/start.php), make sure you include the function in your PHP file.

```php
use function Jaxon\jaxon;
use function Jaxon\jq;
use function Jaxon\rq;
use function Jaxon\pm;
```

**Comment by kskelton2021** [comment]
Thanks for your reply.

I'm on PHP 8.1 & Jaxon 4.1.0 and i got the following error:

Fatal error:  Uncaught Error: Call to a member function files() on null in Upload.class.php:13

My setup looks like this:

```
<?php
// Jaxon Config

require (TPS_DIR . '/jaxon/4.1.0/autoload.php');

use Jaxon\Jaxon;
use function Jaxon\jaxon;

$jaxon = jaxon();
$jaxon->setOption('core.debug.on', 1);
$jaxon->setOption('core.upload.enabled', true);
$jaxon->setOption('upload.default.dir', ROOT_DIR . '/upload');
$jaxon->setOption('upload.default.extensions', ['jpeg', 'jpg', 'JPG']);

$jaxon->register(Jaxon::CALLABLE_CLASS, Upload::class, [
	'include' => ROOT_DIR . '/classes/Jax/Upload.class.php',
	'functions' => [
        'saveFile' => [
            'upload' => "'photoUpload'"
        ]
    ]
]);

if($jaxon->canProcessRequest()){
    $jaxon->processRequest();
}

```
My Jaxon Upload class:

```
<?php
use Jaxon\Response\Response;

class Upload {
  public function saveFile($aFormValues) {
    	$aUploadedFiles = $GLOBALS['jaxon']->upload()->files();
	$images = $aUploadedFiles['image'];

        $num = count($images);
	$i=0;
	foreach($images as $image) {
	    $array = [
            'type' => $image->type(),
            'name' => $image->name(),
            'filename' => $image->filename(),
            'extension' => $image->extension(),
            'size' => $image->size(),
            'path' => $image->path(),
	    ];
         }
    
        $response = $GLOBALS['jaxon']->newResponse();
	$response->assign("msg","innerHTML", "Upload Successful!");
	return $response;
  }
}

```
HTML Upload Form

```
<form method="post" enctype="multipart/form-data" onsubmit="JaxonUpload.saveFile(jaxon.getFormValues(imgupload)); return false;" id="imgupload" class="p-0">
    <div class="form-group row m-0 mb-2">
        <label for="inputCategory" class="col-sm-2 col-form-label px-0">Upload Image File</label>
        <div class="col-8 col-sm-4 p-0">
            <input type="file" class="form-control" id="photoUpload" aria-describedby="inputGroupFileAddon01" name="image[]" multiple="multiple">
        </div>
        <div class="col-4 col-sm-2 pr-0" id="uplBtn">
            <input type="submit" class="btn btn-primary btn-block" value="Upload" name="action" disabled>
        </div>
    </div>
</form>
```

**Comment by feuzeu** [comment]
Hi,

Have you installed the jaxon-core and jaxon-upload packages with Composer?

**Comment by kskelton2021** [comment]
I used composer for jaxon-core and downloaded jaxon-upload from here on github.

**Comment by kskelton2021** [comment]
im really at a lost because I have installed jaxon-core and jaxon-upload now with composer and i get the following error: Fatal error: Uncaught Error: Call to undefined function Jaxon\jaxon() in C:\local_html\assets\vendors\jaxon\4.1.0\jaxon-php\jaxon-upload\src\start.php:86 

Please help....

**Comment by kskelton2021** [comment]
please help! im really trying to move pass this and its completely not working.

**Comment by kskelton2021** [comment]
how long does it really take to get any support for Jaxon... I am requesting help now for 10 days... Should i just abandon Jaxon and move on?

**Comment by kskelton2021** [comment]
sorry for being a bother... im moving on from Jaxon. Its apparent now that Jaxon is not a seriously developed software for use as there is no way to get help and there is no documentation when there are new versions.
